name: flutter_uploader_example
version: 1.2.0
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

dependencies:
  bloc: ^6.0.3
  crypto: ^2.1.4
  flutter:
    sdk: flutter
  file_picker: ^1.13.0
  flutter_bloc: ^6.0.5
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  shared_preferences: ^0.5.8
  flutter_local_notifications: ^1.4.4+2

dev_dependencies:
  e2e: ^0.6.1
  flutter_test:
    sdk: flutter

  flutter_uploader:
    path: ../

dependency_overrides:
  flutter_local_notifications:
    git:
      url: https://github.com/ened/flutter_local_notifications.git
      path: flutter_local_notifications
      ref: 17-notification-actions
  flutter_local_notifications_platform_interface:
    git:
      url: https://github.com/ened/flutter_local_notifications.git
      path: flutter_local_notifications_platform_interface
      ref: 17-notification-actions

flutter:
  uses-material-design: true
