name: flutter_uploader
description: background upload plugin for flutter
version: 1.2.0
homepage: https://github.com/BlueChilli/flutter_uploader

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.2
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bluechilli.flutteruploader
    pluginClass: FlutterUploaderPlugin
