name: format + publishable

on: push

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: axel-op/googlejavaformat-action@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Format
        run: |
          flutter format --set-exit-if-changed .

  publishable:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Test
        run: |
          flutter pub get
          flutter pub publish -n
          pub global activate tuneup
          pub global run tuneup check